# MD013/line-length : Line length : https://github.com/DavidAnson/markdownlint/blob/v0.34.0/doc/md013.md
MD013:
  line_length: 120
  heading_line_length: 80
  code_block_line_length: 120
  code_blocks: true
  tables: true
  headings: true
  strict: false
  stern: false
