name: status checks
on:
  push:
    branches:
      - main
      - master
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  misspell:
    name: runner / misspell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-misspell@v1
        with:
          level: info
          reporter: github-check
          filter_mode: nofilter
          locale: "US"

  typos:
    name: runner / typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-typos@v1
        with:
          level: info
          reporter: github-check
          filter_mode: nofilter

  markdownlint:
    name: runner / markdownlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-markdownlint@v0
        with:
          level: info
          reporter: github-check
          filter_mode: nofilter

  shfmt:
    name: runner / shfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-shfmt@v1
        with:
          level: info
          reporter: github-check
          filter_mode: nofilter
          fail_on_error: true
          shfmt_flags: '-ln bash -ci -sr -i 2'

  shellcheck:
    name: runner / shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          level: info
          reporter: github-check
          filter_mode: nofilter
          fail_on_error: true
          exclude: |
            "./.git/*"
