name: status checks
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  linters:
    name: run linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6.0.2
      - uses: reviewdog/action-misspell@d6429416b12b09b4e2768307d53bef58d172e962 # ratchet:reviewdog/action-misspell@v1.27.0
        name: misspell
        with:
          locale: "US"
      - uses: reviewdog/action-typos@d5eb1bbcd1b3bfde596f6eeb470322727862fe98 # ratchet:reviewdog/action-typos@v1.19.0
        name: typos
      - uses: reviewdog/action-shfmt@d8f080930b9be5847b4f97e9f4122b81a82aaeac # ratchet:reviewdog/action-shfmt@v1.0.4
        name: shfmt
        with:
          shfmt_flags: '-ci -sr -i 2'
      - uses: reviewdog/action-shellcheck@4c07458293ac342d477251099501a718ae5ef86e # ratchet:reviewdog/action-shellcheck@v1.32.0
        name: shellcheck
        with:
          fail_level: any
          exclude: |
            "./.git/*"
      - uses: reviewdog/action-markdownlint@3667398db9118d7e78f7a63d10e26ce454ba5f58 # ratchet:reviewdog/action-markdownlint@v0.26.2
        name: markdownlint
        with:
          fail_level: any

  tests:
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6.0.2
      - run: cd test && ./test.sh
        env:
          TMPDIR: ${{ runner.temp }}
